# Generated by Django 4.0.6 on 2022-09-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_order_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Complete', 'Order complete'), ('On The Way', 'On The Way'), ('Order Processing', 'Order Processing'), ('Order Cancel', 'Order Cancel')], default='Order Received', max_length=255),
        ),
    ]
